plugins {
    id 'com.android.application'
}

android {
    compileSdk = 37

    defaultConfig {
        applicationId "com.jcrawley.webradio"
        minSdk = 33
        targetSdk = 37
        versionCode 7
        versionName "1.3"

        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
    compileOptions {
    }
    namespace 'com.jcrawley.webradio'
}

dependencies {
    implementation 'androidx.appcompat:appcompat:1.8.0'
    implementation 'com.google.android.material:material:1.14.0'
    implementation 'androidx.constraintlayout:constraintlayout:2.2.2'
    testImplementation 'junit:junit:5'
    androidTestImplementation 'androidx.test.ext:junit:1.3.0'
    androidTestImplementation 'androidx.test.espresso:espresso-core:3.7.0'
}